SELECT
  src.`row_id` AS `row_id`,
  src.`event_date` AS `event_date`,
  src.`region` AS `region`,
  src.`channel` AS `channel`,
  src.`scenario_version` AS `scenario_version`,
  src.`stage` AS `stage`,
  src.`stage_order` AS `stage_order`,
  src.`acquisitions` AS `acquisitions`,
  src.`cost` AS `cost`,
  src.`type_date` AS `type_date`,
  toTypeName(src.`type_date`) AS `type_date_native_type`,
  toString(src.`type_date32`) AS `type_date32`,
  toTypeName(src.`type_date32`) AS `type_date32_native_type`,
  src.`type_datetime` AS `type_datetime`,
  toTypeName(src.`type_datetime`) AS `type_datetime_native_type`,
  src.`type_datetime32` AS `type_datetime32`,
  toTypeName(src.`type_datetime32`) AS `type_datetime32_native_type`,
  toString(src.`type_datetime64`) AS `type_datetime64`,
  toTypeName(src.`type_datetime64`) AS `type_datetime64_native_type`,
  toString(src.`type_time`) AS `type_time`,
  toTypeName(src.`type_time`) AS `type_time_native_type`,
  toString(src.`type_time64`) AS `type_time64`,
  toTypeName(src.`type_time64`) AS `type_time64_native_type`,
  toString(src.`type_enum8`) AS `type_enum8`,
  toTypeName(src.`type_enum8`) AS `type_enum8_native_type`,
  toString(src.`type_enum16`) AS `type_enum16`,
  toTypeName(src.`type_enum16`) AS `type_enum16_native_type`,
  toString(src.`type_enum`) AS `type_enum`,
  toTypeName(src.`type_enum`) AS `type_enum_native_type`,
  src.`type_string` AS `type_string`,
  toTypeName(src.`type_string`) AS `type_string_native_type`,
  toString(src.`type_fixedstring`) AS `type_fixedstring`,
  toTypeName(src.`type_fixedstring`) AS `type_fixedstring_native_type`,
  toString(src.`type_uuid`) AS `type_uuid`,
  toTypeName(src.`type_uuid`) AS `type_uuid_native_type`,
  toString(src.`type_ipv4`) AS `type_ipv4`,
  toTypeName(src.`type_ipv4`) AS `type_ipv4_native_type`,
  toString(src.`type_ipv6`) AS `type_ipv6`,
  toTypeName(src.`type_ipv6`) AS `type_ipv6_native_type`,
  toJSONString(src.`type_array`) AS `type_array`,
  toTypeName(src.`type_array`) AS `type_array_native_type`,
  toJSONString(src.`type_tuple`) AS `type_tuple`,
  toTypeName(src.`type_tuple`) AS `type_tuple_native_type`,
  toJSONString(src.`type_map`) AS `type_map`,
  toTypeName(src.`type_map`) AS `type_map_native_type`,
  toJSONString(src.`type_nested`) AS `type_nested`,
  toTypeName(src.`type_nested`) AS `type_nested_native_type`,
  CAST(src.`type_nullable`, 'Nullable(Int64)') AS `type_nullable`,
  toTypeName(src.`type_nullable`) AS `type_nullable_native_type`,
  CAST(src.`type_lowcardinality`, 'String') AS `type_lowcardinality`,
  toTypeName(src.`type_lowcardinality`) AS `type_lowcardinality_native_type`,
  CAST(src.`type_array`, 'Array(Int64)') AS `array_int`,
  arrayMap(x -> toFloat64(x) / 10.0, src.`type_array`) AS `array_float`,
  arrayMap(x -> concat('item-', toString(x)), src.`type_array`) AS `array_str`,
  src.`type_uuid` AS `uuid_value`
FROM __TABLE_ACQUISITION__ AS src
