SELECT
  src.`row_id` AS `row_id`,
  src.`event_date` AS `event_date`,
  src.`region` AS `region`,
  src.`channel` AS `channel`,
  src.`scenario_version` AS `scenario_version`,
  src.`route` AS `route`,
  src.`point_order` AS `point_order`,
  src.`latitude` AS `latitude`,
  src.`longitude` AS `longitude`,
  src.`polygon_json` AS `polygon_json`,
  src.`deliveries` AS `deliveries`,
  src.`duration_minutes` AS `duration_minutes`,
  src.`priority` AS `priority`,
  src.`start_time` AS `start_time`,
  src.`end_time` AS `end_time`,
  toJSONString(src.`type_point`) AS `type_point`,
  toTypeName(src.`type_point`) AS `type_point_native_type`,
  toJSONString(src.`type_ring`) AS `type_ring`,
  toTypeName(src.`type_ring`) AS `type_ring_native_type`,
  toJSONString(src.`type_linestring`) AS `type_linestring`,
  toTypeName(src.`type_linestring`) AS `type_linestring_native_type`,
  toJSONString(src.`type_polygon`) AS `type_polygon`,
  toTypeName(src.`type_polygon`) AS `type_polygon_native_type`,
  toJSONString(src.`type_multilinestring`) AS `type_multilinestring`,
  toTypeName(src.`type_multilinestring`) AS `type_multilinestring_native_type`,
  toJSONString(src.`type_multipolygon`) AS `type_multipolygon`,
  toTypeName(src.`type_multipolygon`) AS `type_multipolygon_native_type`,
  toJSONString(src.`type_json`) AS `type_json`,
  toTypeName(src.`type_json`) AS `type_json_native_type`,
  toString(src.`type_dynamic`) AS `type_dynamic`,
  toTypeName(src.`type_dynamic`) AS `type_dynamic_native_type`,
  toString(src.`type_variant`) AS `type_variant`,
  toTypeName(src.`type_variant`) AS `type_variant_native_type`,
  toJSONString(CAST(src.`type_object` AS JSON)) AS `type_object`,
  toTypeName(src.`type_object`) AS `type_object_native_type`
FROM __TABLE_DELIVERY__ AS src
