"""Shared table operations and validation helpers used by load and transfer flows."""

from .ch_reconfigure import ch_reconfigure_table
from .drop_tables import drop_tables
from .models import (
    ChCreateTableAsOptions,
    ChDropTableOptions,
    CreateTableFromSqlOptions,
    DropManyPartitionsOptions,
)
from .api import (
    analyze_table,
    build_analyze_table_sql,
    build_clear_table_sqls,
    build_count_table_rows_sql,
    build_drop_ch_distributed_table_pair_sqls,
    build_drop_many_partitions_sqls,
    build_drop_table_sql,
    clear_target_table,
    build_insert_from_query_sql,
    build_insert_from_table_sql,
    count_table_rows,
    drop_table_with_retry,
    finalize_stage_table,
    get_table_column_types,
    get_trino_table_column_types,
    gp_create_partitions,
    gp_vacuum,
    insert_from_query,
    insert_from_table,
    table_exists,
)
from .table_validation import (
    normalize_key_columns,
    normalize_upsert_partition_column,
    validate_key_columns_in_columns,
    validate_stage_target_key_overlap,
    validate_stage_uniqueness,
    validate_upsert_partition_column_in_columns,
)
from .partitions import drop_partitions

__all__ = [
    "analyze_table",
    "build_analyze_table_sql",
    "build_clear_table_sqls",
    "build_count_table_rows_sql",
    "build_drop_ch_distributed_table_pair_sqls",
    "build_drop_many_partitions_sqls",
    "build_drop_table_sql",
    "ChCreateTableAsOptions",
    "ChDropTableOptions",
    "ch_reconfigure_table",
    "clear_target_table",
    "build_insert_from_query_sql",
    "build_insert_from_table_sql",
    "count_table_rows",
    "CreateTableFromSqlOptions",
    "drop_partitions",
    "DropManyPartitionsOptions",
    "drop_tables",
    "drop_table_with_retry",
    "finalize_stage_table",
    "get_table_column_types",
    "get_trino_table_column_types",
    "gp_create_partitions",
    "gp_vacuum",
    "insert_from_query",
    "insert_from_table",
    "normalize_key_columns",
    "normalize_upsert_partition_column",
    "table_exists",
    "validate_key_columns_in_columns",
    "validate_stage_target_key_overlap",
    "validate_stage_uniqueness",
    "validate_upsert_partition_column_in_columns",
]
